spring.application.name=demo

spring.datasource.url=jdbc:h2:file:./data/todo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Flyway - niech zarz?dza tabelami
spring.flyway.enabled=true

# To pozwoli Ci podgl?da? baz? w przegl?darce pod localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA - nie pozwól Hibernate usuwa? tabel przy starcie!
spring.jpa.hibernate.ddl-auto=validate